# Generated by Django 5.0.7 on 2025-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("question", "Вопрос"),
                            ("offer", "Предложение"),
                            ("complaint", "Жалоба"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=2000, verbose_name="Сообщение"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
