# Generated by Django 5.0.7 on 2025-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, verbose_name="Ссылка")),
                (
                    "og_image",
                    models.CharField(
                        max_length=255, verbose_name="Картинка для социальных сетей"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок в результатах поиска"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(verbose_name="Описание в результатах поиска"),
                ),
                (
                    "og_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок для социальных сетей"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(verbose_name="Описание для социальных сетей"),
                ),
                (
                    "canonical",
                    models.CharField(
                        max_length=255, verbose_name="Каноническая ссылка"
                    ),
                ),
                (
                    "is_no_index",
                    models.BooleanField(default=False, verbose_name="Нет индексации"),
                ),
                (
                    "is_no_follow",
                    models.BooleanField(default=False, verbose_name="Нет следования"),
                ),
            ],
            options={
                "verbose_name": "SEO",
                "verbose_name_plural": "SEO",
            },
        ),
    ]
