# Generated by Django 5.0.7 on 2025-03-09 10:42

import common.functions
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название марки"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.functions.get_path_for_avatar_brand,
                        verbose_name="Значок",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        choices=[
                            ("sedan", "Седан"),
                            ("hatchback", "Хэтчбэк"),
                            ("crossover", "Кроссовер"),
                            ("pickup", "Пикап"),
                            ("van", "Ван"),
                            ("minivan", "Минивэн"),
                            ("cabriolet", "Кабриолет"),
                            ("coupe", "Купе"),
                        ],
                        default="sedan",
                        max_length=50,
                        verbose_name="Тип кузова",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Черный"),
                            ("white", "Белый"),
                            ("blue", "Синий"),
                            ("red", "Красный"),
                            ("gray", "Серый"),
                            ("yellow", "Желтый"),
                            ("green", "Зеленый"),
                        ],
                        default="black",
                        max_length=50,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("auto", "Автомат"),
                            ("mech", "Механическая"),
                            ("robot", "Роботизированная"),
                            ("vari", "Вариатор"),
                        ],
                        default="auto",
                        max_length=50,
                        verbose_name="Трансмиссия",
                    ),
                ),
                (
                    "drive",
                    models.CharField(
                        choices=[
                            ("front", "Передний"),
                            ("back", "Задний"),
                            ("all", "Полный"),
                        ],
                        default="front",
                        max_length=50,
                        verbose_name="Привод",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("new", "Новый"), ("used", "Б/У")],
                        default="new",
                        max_length=50,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(blank=True, null=True, verbose_name="Пробег"),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, null=True, verbose_name="Цена"),
                ),
                ("sale", models.BooleanField(default=False, verbose_name="Акция")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.functions.get_path_for_avatar_car,
                        verbose_name="Значок",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descount",
                    models.IntegerField(blank=True, null=True, verbose_name="Скидка"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Условия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
        migrations.CreateModel(
            name="ImageCar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.functions.get_path_for_all_images_by_car,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="ModelCar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название модели"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.brand",
                        verbose_name="Марка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="model_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cars.modelcar",
                verbose_name="Модель",
            ),
        ),
    ]
