# Generated by Django 5.0.7 on 2025-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_color_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="descount",
            new_name="discount",
        ),
        migrations.AddField(
            model_name="car",
            name="total_sum",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Итоговая цена"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Проверен"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("russia", "Россия"),
                    ("germany", "Германия"),
                    ("japan", "Япония"),
                    ("china", "Китай"),
                    ("sweden", "Швеция"),
                    ("france", "Франция"),
                ],
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
