# Generated by Django 5.0.7 on 2025-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_rename_descount_sale_discount_car_total_sum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("russia", "Россия"),
                    ("germany", "Германия"),
                    ("japan", "Япония"),
                    ("china", "Китай"),
                    ("sweden", "Швеция"),
                    ("france", "Франция"),
                    ("korea", "Корея"),
                ],
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
